### ISSUE TITLE
Language=en

### ISSUE THREAD

**Issue by Stefan-Espant** [christoph3r3w/look-and-feel-living-styleguide#1]
Check of deze waarde in het Engels moet staan of in het Nederlands.

https://github.com/christoph3r3w/look-and-feel-living-styleguide/blob/a082659ff03c2905d2df53f82e12b6240742ba75/index.html#L2C15-L2C17

**Comment by christoph3r3w** [comment]
Sinds dat het een Neverlands website is, moet de "lang" ook NL zijn. Dus ik ga het aanpassen. thanks
