### ISSUE TITLE
Gaaf dat je al custom-properties gebruikt!

### ISSUE THREAD

**Issue by Stefan-Espant** [christoph3r3w/look-and-feel-living-styleguide#2]
Hiermee kan je bijv. het kleurcontrast in een media query plaatsen en vervolgens de DRY methode gebruiken.
Check of je ook semantische namen kan gebruiken ipv de kleur zelf. Stel je wilt je site een dark/light functie geven, is wit dan nog wit?

https://github.com/christoph3r3w/look-and-feel-living-styleguide/blob/0969e62175ac868ca42bccb905b51e3199278d62/styles/style.css#L33-L45

**Comment by christoph3r3w** [comment]
Ja, het is handig en het helpt met consistentie op de website.

**Comment by Stefan-Espant** [comment]
Exact en je herhaalt jezelf hiermee niet.
